# Generated by Django 6.0.2 on 2026-02-13 20:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="wallet_balance",
            field=models.DecimalField(decimal_places=2, default=100.0, max_digits=12),
        ),
    ]
